#management.endpoints.web.exposure.include=*
server.port=8888
#enregistre toi !
spring.cloud.discovery.enabled=true
spring.application.name=gateway-service
#pour lui dire à quelle adresse s'enregistrer
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
logging.level.org.springframework.web=DEBUG



